<?php
    $ticket = $block->getCurrentTicket();
?>
<?php
    $property = [
        'Department' => $ticket->getDepartmentName(),
        'Status'     => $ticket->getStatusName(),
        'Priority'   => $ticket->getPriorityLabel()
    ];
?>
<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?= $block->escapeHtml(__(
            'Ticket #%1 - "%2"',
            $ticket->getNumber(),
            trim($ticket->getTitle())
        ))
    ?></span>
    </h1>
    <span class="order-status"><?= $block->escapeHtml(__($ticket->getStatusName())) ?></span>
    <div class="ticket-basic-info">
        <div class="ticket-date">
            <?= /* @noEscape */ __('<span class="label">Ticket Date:</span> %1', '<date>' . $block->formatDate($ticket->getCreatedAt(), \IntlDateFormatter::LONG) . '</date>') ?>
        </div>
        <div class="div-cancel">
            <a class="ticket-close-link" href="<?= $block->getClostTicketUrl() ?>">
                <button type="button" title="cancel" class="action submit primary">
                    <span>Close Ticket</span>
                </button>
            </a>
        </div>
    </div>
</div>
<div class="block block-helpdesk-ticket-view">
    <div class="block-content">
        <div class="ticket-info">
            <dl>
                <?php foreach ($property as $label => $value) : ?>
                    <div class="field ticket-info-view">
                        <label class="label"><?= $block->escapeHtml(__($label)) ?></label>
                        <div class="control"><span><?= $block->escapeHtml(__($value)) ?></span></div>
                    </div>
                <?php endforeach;?>
            </dl>
        </div>
        <?= /* @noEscape */ $block->getChildHtml('messages'); ?>
        <?= /* @noEscape */ $block->getChildHtml('new_message'); ?>
    </div>
</div>