<?php

    $ticket = $block->getCurrentTicket();
    if (!$ticket) {
        return;
    }
?>
<div class="block">
    <div class="title block-title">
        <strong><?= $block->escapeHtml(__('Add New Message')) ?></strong>
    </div>
    <div class="block-content">
        <form action="<?= $block->escapeUrl($block->getAction()); ?>" method="post" id="helpdesk-new-message-form" data-mage-init='{"validation":{}}'>
            <div class="field note no-label">
                <?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')); ?>
            </div>
            <fieldset class="fieldset">
                <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
                <input name="ticket_id" type="hidden" value=<?= /* @escapeNotVerified */ $block->escapeHtmlAttr($ticket->getTicketId())?>>
                <div class="field text required">
                    <label class="label" for="message_text"><span><?= $block->escapeHtml(__('Message')); ?></span></label>
                    <div class="control">
                        <textarea name="text" id="message_text" title="<?= $block->escapeHtmlAttr(__('Message')); ?>" class="input-text" cols="5" rows="5" data-validate="{required:true}"></textarea>
                    </div>
                </div>
            </fieldset>
            
            <div class="upload-wrapper" data-bind="scope: 'uploader'">
            <!-- ko template: getTemplate() --><!-- /ko -->
            </div>

            <script type="text/x-magento-init">
            {
               ".upload-wrapper": {
                   "Magento_Ui/js/core/app": {
                       "components": {
                           "uploader": {
                               "component": "Magento_Ui/js/form/element/file-uploader",
                               "template": "MagePrakash_Helpdesk/uploader",
                               "previewTmpl":"MagePrakash_Helpdesk/attachment-preview",
                               "isMultipleFiles":true,
                               "uploaderConfig": {
                                    "url": "<?php echo $block->getUrl('helpdesks/ticketMessage/addAttachment'); ?>"
                               }
                           }
                       }
                   }
               }
            }
            </script>
            
         <!--    <input type="checkbox" name="is_cancel" id="is_cancel" ><label for="is_cancel"><?= __('Ticket Cancel') ?></label> -->

            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" title="<?= $block->escapeHtml(__('Submit')); ?>" class="action submit primary">
                        <span><?= $block->escapeHtml(__('Submit')); ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
